enum Error {
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  RECOVERY_TOKEN_EXPIRED_OR_INVALID = 'RECOVERY_TOKEN_EXPIRED_OR_INVALID',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EXISTING_ACCOUNT = 'EXISTING_ACCOUNT',
}

export default Error;
