export enum ReportOwnerType {
  COMPANY = 'COMPANY',
  USER = 'USER',
}

export enum ReportSubType {
  SUCCESS_PROFILE_FULL = 'SUCCESS_PROFILE_FULL',
  SUCCESS_PROFILE_PARTIAL = 'SUCCESS_PROFILE_PARTIAL',
  CANDIDATE_RESULTS_CANDIDATE = 'CANDIDATE_RESULTS_CANDIDATE',
  CANDIDATE_RESULTS_MANAGER = 'CANDIDATE_RESULTS_MANAGER',
  CANDIDATE_RESULTS_MANAGER_EXTENDED = 'CANDIDATE_RESULTS_MANAGER_EXTENDED',
}

export enum ReportType {
  CANDIDATE_RESULTS = 'CANDIDATE_RESULTS',
  SUCCESS_PROFILE = 'SUCCESS_PROFILE',
}
