export enum ContentRoleLevel {
  INDIVIDUAL_CONTRIBUTOR = 'INDIVIDUAL_CONTRIBUTOR',
  MANAGER = 'MANAGER',
  MANAGER_OF_MANAGERS = 'MANAGER_OF_MANAGERS',
  LEADER = 'LEADER',
  APPRENTICE = 'APPRENTICE',
  TECHNICAL_EXPERT = 'TECHNICAL_EXPERT',
}

export enum SoftSkillType {
  DIFFERENTIATOR = 'DIFFERENTIATOR',
  CORE = 'CORE',
  DIVERSITY = 'DIVERSITY',
}

export enum SoftSkillDataSourceType {
  INDUSTRY = 'INDUSTRY',
  JD_REVIEW = 'JD_REVIEW',
  MANAGER_SURVEY = 'MANAGER_SURVEY',
  EMPLOYEE_SURVEY = 'EMPLOYEE_SURVEY',
  EMPLOYEE_ASSESSMENT = 'EMPLOYEE_ASSESSMENT',
}
