export enum Tests {
  PERSONALITY = 'PERSONALITY',
  MOTIVATION = 'MOTIVATION',
  NUMERICAL = 'NUMERICAL',
  INDUCTIVE = 'INDUCTIVE',
  VERBAL = 'VERBAL',
  COGNITIVE_COMBINED = 'COGNITIVE_COMBINED',
}
