export enum AuthViews {
  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  RESTORE_PASSWORD = 'RESTORE_PASSWORD',
  CREATE_PASSWORD = 'CREATE_PASSWORD',
  TWO_FACTOR_AUTHENTICATION = 'TWO_FACTOR_AUTHENTICATION',
}
